sudo: required
services:
  - docker

before_install:
  - docker build -t aruprakshit/react-app-dockerized -f Dockerfile.dev .

script:
  - docker run aruprakshit/react-app-dockerized npm run test -- --coverage
